### ISSUE TITLE
Make list of GSIM mapping

### ISSUE THREAD

**Issue by borsna** [ddialliance/lion#27]
Show list
GSIM | DDI 4

**Comment by borsna** [comment]
Johanna worked on this in the London-sprint:
http://lion.ddialliance.org/mapping/ddi3-2
http://lion.ddialliance.org/mapping/gsim

Don´t know if it´s final?

**Comment by jvompras** [comment]
Implemented as lists
http://lion.ddialliance.org/mapping/ddi3-2
http://lion.ddialliance.org/mapping/gsim
