### ISSUE TITLE
Frontispiece for each release package

### ISSUE THREAD

**Issue by wlthomas** [ddialliance/lion#29]
BUILD INFORMATION for release:

```
Build date / version
Release Title
Included packages/views
Executive summary that summarizes the build
Standard text regarding status of content
Copyright/license
```

Homes for this material should be available in Drupal on the section containing released content

DocBook Frontispiece

**Comment by borsna** [comment]
accc:s comments from #25 (should be in this issue instead)
THINGS IN angle brackets disappear 
here it is again

Frontispiece is wrapped in info?
Release Title - title?
Sub Title - subtitle?
Year - year?
Version - productnumber?
Copyright - productname class='copyright'?
Date of publication - date? 
Legal Notice - legalnotice?
Release information - acknowledgements? releaseinfo?
Preface - para?
Contact Information - para?
Authors:
author?
personname?
firstname? 
surname?
affiliation?
orgname?
Logo 
mediaobject?
imageobject condition="web"?
imagedata fileref=".png" format="PNG" scale=""?

**Comment by borsna** [comment]
Some of these are editable in drupal and outputed in the docbook xml.
To edit: http://lion.ddialliance.org/node/743/edit

**Comment by spuddybike** [comment]
This can be closed - as we are no longer using docbook
