### ISSUE TITLE
More link (paging) is not working on pages or views using VIEWS PHP 

### ISSUE THREAD

**Issue by jvompras** [ddialliance/lion#33]
e.g. http://lion.ddialliance.org/content-revisions-summary

Well-known problem discussed here, patch does not work
https://www.drupal.org/node/2276165

**Comment by jfihn** [comment]
There seems to be a working fix for the 7.x-2.x-dev version of Views PHP here https://www.drupal.org/node/2484407

**Comment by jvompras** [comment]
Working by VIEW-PHP update (dev version 7.x-2.x-dev) and applying the patch. (views_php_pager.patch)
