### ISSUE TITLE
Bug in the graph generator

### ISSUE THREAD

**Issue by mhebing** [ddialliance/lion#37]
http://lion.ddialliance.org/package/complexdatatypes

Error: :95: syntax error near line 95 context: DDI_BasedOnObject:BasedOnObjectbasedOn -> DDI_Identifiable [side= >>> arrowhead= <<< open labeldistance=1.9 taillabel="1..1" headlabel="0..n" edgetooltip="basedOn" fontcolor="black" color="#00000"];

**Comment by borsna** [comment]
Fixed
