### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by FlavioRizzolo** [ddialliance/lion#44]
Some relationships are not rendered. I have identified the following:
•	ConceptParentChild: parent and child 
•	ConceptPartWhole: part and whole 
•	ContainsTemporalRelation: contains and during
•	EqualTemporalRelation: equalA and equalB
•	FinishesTemporalRelation: finishedBy and finishes

There are also two errors displayed in the graph, which seem to be related:

Error: :50: syntax error near line 50 context: DDI_ConceptParentChild:ConceptParentChildparent -> DDI_Concept [side= >>> arrowhead= <<< none labeldistance=1.9 taillabel="0..n" headlabel="1..1" edgetooltip="parent" fontcolor="black" color="#00000"];

Error: :52: syntax error near line 52 context: DDI_ContainsTemporalRelation:ContainsTemporalRelationcontains -> DDI_ProcessStep [side= >>> arrowhead= <<< none labeldistance=1.9 taillabel="0..1" headlabel="1..1" edgetooltip="contains" fontcolor="black" color="#00000"];

**Comment by FlavioRizzolo** [comment]
These screenshots show the missing associations in yellow:

![conceptual](https://cloud.githubusercontent.com/assets/11507347/6672636/2b0ea54e-cbe4-11e4-8fd1-58c13ad6ad8c.PNG)

![coreprocess](https://cloud.githubusercontent.com/assets/11507347/6672644/33365f78-cbe4-11e4-9b22-fdc9a48a240d.PNG)

**Comment by FlavioRizzolo** [comment]
URLs:

http://lion.ddialliance.org/package/conceptual
http://lion.ddialliance.org/package/coreprocess

**Comment by accc** [comment]
This is also happening on http://lion.ddialliance.org/ddiobjects/agentassociation

**Comment by borsna** [comment]
This should now be fixed:
could you verify?
![conceptual](https://cloud.githubusercontent.com/assets/794445/7133960/a3fed526-e298-11e4-8aa2-dbeeb574b7be.png)

**Comment by accc** [comment]
You are Sir,  a genius – and we bow down before you ☺

Jon

**Comment by FlavioRizzolo** [comment]
It is fixed. Thanks!!

Flavio
