### ISSUE TITLE
xml:lang is not valid in an ID in docbook

### ISSUE THREAD

**Issue by accc** [ddialliance/lion#48]
See for example when running it through xsltproc

ddi4.2015-04-06.docbook_10.xml:176: validity error : xml:id : attribute value ddi4-bd40e585-58a4-409a-8b9e-85e6719ecc04-properties-xml:lang is not an NCName
 <section xml:id="ddi4-bd40e585-58a4-409a-8b9e-85e6719ecc04-properties-xml:lang"

**Comment by jfihn** [comment]
This is due to the object Note in the Utility package having a property named xml:lang, causing the id of the attribute to contain an illegal character (:).

**Comment by accc** [comment]
yup I know - but its still invalid :(

**Comment by jfihn** [comment]
If I understand it correctly, this is just an internal id used in the docbook xml. Replacing all : with _ to fix this error.

**Comment by accc** [comment]
thanks
