### ISSUE TITLE
More granularity on section output to docbook

### ISSUE THREAD

**Issue by ucl-cls** [ddialliance/lion#49]
Currently all sections have the same level. This makes it impossible to suppress sub-sections.

We should use sect1, sect2 etc to differentiate so that we can for instance not display sect2 in tables of content.

**Comment by borsna** [comment]
trying to find examples of how to do this in docbook xml, could you provide an example how to change this in the following case?
i guess its attributes on title?
```xml
<chapter xml:id="ddi4-Identification">
   <title>Identification</title>
   <section xml:id="ddi4-e162060d-a197-456d-9837-d0dad3f78c3d">
      <title>AnnotatedIdentifiable</title>
      <section revision="" role="extends">
         <title>Extends</title>
         <para>
            This object extends
            <link linkend="ddi4-0411fa15-42da-4060-b78d-558b9086d700">
            Identifiable</link>
         </para>
      </section>
      <section revision="" role="is_abstract">
         <title>Abstract</title>
         <para>This class is abstract</para>
      </section>
      <section xml:id="ddi4-e162060d-a197-456d-9837-d0dad3f78c3d-definition" revision="" role="definition">
         <title>Definition</title>
         <para>
            Used to identify objects for purposes of internal and/or external referencing. Elements of this type are versioned. Provides administrative metadata about the object in addition to what is provided by Identifiable, including more details on the versioning of the object. Most objects except for the ComplexDataTypes will inherit AnnotatedIdentfiable.
         </para>
      </section>
      <section xml:id="ddi4-e162060d-a197-456d-9837-d0dad3f78c3d-properties" revision="" role="properties">
         <title>Properties</title>
         <section xml:id="ddi4-e162060d-a197-456d-9837-d0dad3f78c3d-properties-versionResponsibility">
            <title>versionResponsibility</title>
            <informaltable frame="all">
               <tgroup cols="2">
                  <colspec colname="c1" colnum="1" colwidth="1*"/>
                  <colspec colname="c2" colnum="2" colwidth="7.87*"/>
                  <tbody>
                     <row>
                        <entry>Datatype</entry>
                        <entry role="datatype">xs:string</entry>
                     </row>
                     <row>
                        <entry>Cardinality</entry>
                        <entry role="cardinality">0..1</entry>
                     </row>
                     <row>
                        <entry role="description" namest="c1" nameend="c2">
                           Contributor who has the ownership and responsiblity for the current version.
                        </entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
         </section>
         <section xml:id="ddi4-e162060d-a197-456d-9837-d0dad3f78c3d-properties-versionRationale">
            <title>versionRationale</title>
            <informaltable frame="all">
               <tgroup cols="2">
                  <colspec colname="c1" colnum="1" colwidth="1*"/>
                  <colspec colname="c2" colnum="2" colwidth="7.87*"/>
                  <tbody>
                     <row>
                        <entry>Datatype</entry>
                        <entry role="datatype">xs:string</entry>
                     </row>
                     <row>
                        <entry>Cardinality</entry>
                        <entry role="cardinality">0..1</entry>
                     </row>
                     <row>
                        <entry role="description" namest="c1" nameend="c2">The reason for making this version of the object.</entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
         </section>
         <section xml:id="ddi4-e162060d-a197-456d-9837-d0dad3f78c3d-properties-versionDate">
            <title>versionDate</title>
            <informaltable frame="all">
               <tgroup cols="2">
                  <colspec colname="c1" colnum="1" colwidth="1*"/>
                  <colspec colname="c2" colnum="2" colwidth="7.87*"/>
                  <tbody>
                     <row>
                        <entry>Datatype</entry>
                        <entry role="datatype">xs:dateTime</entry>
                     </row>
                     <row>
                        <entry>Cardinality</entry>
                        <entry role="cardinality">0..1</entry>
                     </row>
                     <row>
                        <entry role="description" namest="c1" nameend="c2">The date and time the object was changed.</entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
         </section>
         <section xml:id="ddi4-e162060d-a197-456d-9837-d0dad3f78c3d-properties-isUniversallyUnique">
            <title>isUniversallyUnique</title>
            <informaltable frame="all">
               <tgroup cols="2">
                  <colspec colname="c1" colnum="1" colwidth="1*"/>
                  <colspec colname="c2" colnum="2" colwidth="7.87*"/>
                  <tbody>
                     <row>
                        <entry>Datatype</entry>
                        <entry role="datatype">xs:boolean</entry>
                     </row>
                     <row>
                        <entry>Cardinality</entry>
                        <entry role="cardinality">1..1</entry>
                     </row>
                     <row>
                        <entry role="description" namest="c1" nameend="c2">
                           Usually the combination of agency and id (ignoring different versions) is unique. If isUniversallyUnique is set to true, it indicates that the id itsef is universally unique (unique across systems and/or agencies) and therefore the agency part is not required to ensure uniqueness. Default value is false.
                        </entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
         </section>
         <section xml:id="ddi4-e162060d-a197-456d-9837-d0dad3f78c3d-properties-isPersistent">
            <title>isPersistent</title>
            <informaltable frame="all">
               <tgroup cols="2">
                  <colspec colname="c1" colnum="1" colwidth="1*"/>
                  <colspec colname="c2" colnum="2" colwidth="7.87*"/>
                  <tbody>
                     <row>
                        <entry>Datatype</entry>
                        <entry role="datatype">xs:boolean</entry>
                     </row>
                     <row>
                        <entry>Cardinality</entry>
                        <entry role="cardinality">1..1</entry>
                     </row>
                     <row>
                        <entry role="description" namest="c1" nameend="c2">
                           Usually the content of the current version is allowed to change, for example as the contibutor is working on the object contents. However, when isPersistent is true, it indicates the there will be no more changes to the current version. Default value is false.
                        </entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
         </section>
         <section xml:id="ddi4-e162060d-a197-456d-9837-d0dad3f78c3d-properties-localId">
            <title>localId</title>
            <informaltable frame="all">
               <tgroup cols="2">
                  <colspec colname="c1" colnum="1" colwidth="1*"/>
                  <colspec colname="c2" colnum="2" colwidth="7.87*"/>
                  <tbody>
                     <row>
                        <entry>Datatype</entry>
                        <entry role="datatype">LocalId</entry>
                     </row>
                     <row>
                        <entry>Cardinality</entry>
                        <entry role="cardinality">0..n</entry>
                     </row>
                     <row>
                        <entry role="description" namest="c1" nameend="c2">
                           This is an identifier in a given local context that uniquely references an object, as opposed to the full ddi identifier which has an agency plus the id. For example, localId could be a variable name in a dataset.
                        </entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
         </section>
         <section xml:id="ddi4-e162060d-a197-456d-9837-d0dad3f78c3d-properties-basedOnObject">
            <title>basedOnObject</title>
            <informaltable frame="all">
               <tgroup cols="2">
                  <colspec colname="c1" colnum="1" colwidth="1*"/>
                  <colspec colname="c2" colnum="2" colwidth="7.87*"/>
                  <tbody>
                     <row>
                        <entry>Datatype</entry>
                        <entry role="datatype">BasedOnObject</entry>
                     </row>
                     <row>
                        <entry>Cardinality</entry>
                        <entry role="cardinality">0..1</entry>
                     </row>
                     <row>
                        <entry role="description" namest="c1" nameend="c2">
                           The object/version that this object version is based on.
                        </entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
         </section>
      </section>
      <section xml:id="ddi4-e162060d-a197-456d-9837-d0dad3f78c3d-relationships" revision="" role="relationships">
         <title>Relationships</title>
         <section xml:id="ddi4-e162060d-a197-456d-9837-d0dad3f78c3d-relationships-hasAnnotation">
            <title>hasAnnotation</title>
            <informaltable frame="all">
               <tgroup cols="2">
                  <colspec colname="c1" colnum="1" colwidth="1*"/>
                  <colspec colname="c2" colnum="2" colwidth="7.87*"/>
                  <tbody>
                     <row>
                        <entry>Target</entry>
                        <entry>
                           <link linkend="ddi4-81534c85-a7ad-4bc9-a276-9ec62a285aa9">
                           Annotation</link>
                        </entry>
                     </row>
                     <row>
                        <entry>Type</entry>
                        <entry>Aggregation</entry>
                     </row>
                     <row>
                        <entry>Source Cardinality</entry>
                        <entry>0..1</entry>
                     </row>
                     <row>
                        <entry>Target Cardinality</entry>
                        <entry>1..n</entry>
                     </row>
                     <row>
                        <entry namest="c1" nameend="c2">
                           Provides annotation information on the object to support citation and crediting of the creator(s) of the object.
                        </entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
         </section>
      </section>
   </section>
   <section xml:id="ddi4-0411fa15-42da-4060-b78d-558b9086d700">
      <title>Identifiable</title>
      <section revision="" role="is_abstract">
         <title>Abstract</title>
         <para>This class is abstract</para>
      </section>
      <section xml:id="ddi4-0411fa15-42da-4060-b78d-558b9086d700-definition" revision="" role="definition">
         <title>Definition</title>
         <para>
            Used to identify objects for purposes of internal and/or external referencing. Elements of this type are versioned. Most objects except for the ComplexDataTypes will inherit from Identifiable or the more specialised AnnotatedIdentfiable.
         </para>
      </section>
      <section xml:id="ddi4-0411fa15-42da-4060-b78d-558b9086d700-properties" revision="" role="properties">
         <title>Properties</title>
         <section xml:id="ddi4-0411fa15-42da-4060-b78d-558b9086d700-properties-agency">
            <title>agency</title>
            <informaltable frame="all">
               <tgroup cols="2">
                  <colspec colname="c1" colnum="1" colwidth="1*"/>
                  <colspec colname="c2" colnum="2" colwidth="7.87*"/>
                  <tbody>
                     <row>
                        <entry>Datatype</entry>
                        <entry role="datatype">xs:string</entry>
                     </row>
                     <row>
                        <entry>Cardinality</entry>
                        <entry role="cardinality">1..1</entry>
                     </row>
                     <row>
                        <entry role="description" namest="c1" nameend="c2">
                           This is the registered agency code with optional sub-agencies separated by dots. For example, diw.soep, ucl.qss, abs.essg.
                        </entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
         </section>
         <section xml:id="ddi4-0411fa15-42da-4060-b78d-558b9086d700-properties-id">
            <title>id</title>
            <informaltable frame="all">
               <tgroup cols="2">
                  <colspec colname="c1" colnum="1" colwidth="1*"/>
                  <colspec colname="c2" colnum="2" colwidth="7.87*"/>
                  <tbody>
                     <row>
                        <entry>Datatype</entry>
                        <entry role="datatype">xs:string</entry>
                     </row>
                     <row>
                        <entry>Cardinality</entry>
                        <entry role="cardinality">1..1</entry>
                     </row>
                     <row>
                        <entry role="description" namest="c1" nameend="c2">
                           The ID of the object. This must conform to the allowed structure of the DDI Identifier and must be unique within the declared scope of uniqueness (Agency or Maintainable).
                        </entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
         </section>
         <section xml:id="ddi4-0411fa15-42da-4060-b78d-558b9086d700-properties-version">
            <title>version</title>
            <informaltable frame="all">
               <tgroup cols="2">
                  <colspec colname="c1" colnum="1" colwidth="1*"/>
                  <colspec colname="c2" colnum="2" colwidth="7.87*"/>
                  <tbody>
                     <row>
                        <entry>Datatype</entry>
                        <entry role="datatype">xs:string</entry>
                     </row>
                     <row>
                        <entry>Cardinality</entry>
                        <entry role="cardinality">1..1</entry>
                     </row>
                     <row>
                        <entry role="description" namest="c1" nameend="c2">
                           The version number of the object. The version number is incremented whenever the non-administrative metadata contained by the object changes.
                        </entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
         </section>
      </section>
   </section>
</chapter>
```

**Comment by accc** [comment]
Olof

Its simpler than that, just replace the section tag with sect[1-5]

This should work

<chapter xml:id="ddi4-Identification">
   <title>Identification</title>
   <sect1 xml:id="ddi4-e162060d-a197-456d-9837-d0dad3f78c3d">
      <title>AnnotatedIdentifiable</title>
      <sect2 revision="" role="extends">
         <title>Extends</title>
         <para>
            This object extends
            <link linkend="ddi4-0411fa15-42da-4060-b78d-558b9086d700">
            Identifiable</link>
         </para>
      </sect2>
      <sect2 revision="" role="is_abstract">
         <title>Abstract</title>
         <para>This class is abstract</para>
      </sect2>
      <sect2 xml:id="ddi4-e162060d-a197-456d-9837-d0dad3f78c3d-definition" revision="" role="definition">
         <title>Definition</title>
         <para>
            Used to identify objects for purposes of internal and/or external referencing. Elements of this type are versioned. Provides administrative metadata about the object in addition to what is provided by Identifiable, including more details on the versioning of the object. Most objects except for the ComplexDataTypes will inherit AnnotatedIdentfiable.
         </para>
      </sect2>
      <sect2 xml:id="ddi4-e162060d-a197-456d-9837-d0dad3f78c3d-properties" revision="" role="properties">
         <title>Properties</title>
         <sect3 xml:id="ddi4-e162060d-a197-456d-9837-d0dad3f78c3d-properties-versionResponsibility">
            <title>versionResponsibility</title>
            <informaltable frame="all">
               <tgroup cols="2">
                  <colspec colname="c1" colnum="1" colwidth="1*"/>
                  <colspec colname="c2" colnum="2" colwidth="7.87*"/>
                  <tbody>
                     <row>
                        <entry>Datatype</entry>
                        <entry role="datatype">xs:string</entry>
                     </row>
                     <row>
                        <entry>Cardinality</entry>
                        <entry role="cardinality">0..1</entry>
                     </row>
                     <row>
                        <entry role="description" namest="c1" nameend="c2">
                           Contributor who has the ownership and responsiblity for the current version.
                        </entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
         </sect3>
         <sect3 xml:id="ddi4-e162060d-a197-456d-9837-d0dad3f78c3d-properties-versionRationale">
            <title>versionRationale</title>
            <informaltable frame="all">
               <tgroup cols="2">
                  <colspec colname="c1" colnum="1" colwidth="1*"/>
                  <colspec colname="c2" colnum="2" colwidth="7.87*"/>
                  <tbody>
                     <row>
                        <entry>Datatype</entry>
                        <entry role="datatype">xs:string</entry>
                     </row>
                     <row>
                        <entry>Cardinality</entry>
                        <entry role="cardinality">0..1</entry>
                     </row>
                     <row>
                        <entry role="description" namest="c1" nameend="c2">The reason for making this version of the object.</entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
         </sect3>
         <sect3 xml:id="ddi4-e162060d-a197-456d-9837-d0dad3f78c3d-properties-versionDate">
            <title>versionDate</title>
            <informaltable frame="all">
               <tgroup cols="2">
                  <colspec colname="c1" colnum="1" colwidth="1*"/>
                  <colspec colname="c2" colnum="2" colwidth="7.87*"/>
                  <tbody>
                     <row>
                        <entry>Datatype</entry>
                        <entry role="datatype">xs:dateTime</entry>
                     </row>
                     <row>
                        <entry>Cardinality</entry>
                        <entry role="cardinality">0..1</entry>
                     </row>
                     <row>
                        <entry role="description" namest="c1" nameend="c2">The date and time the object was changed.</entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
         </sect3>
         <sect3 xml:id="ddi4-e162060d-a197-456d-9837-d0dad3f78c3d-properties-isUniversallyUnique">
            <title>isUniversallyUnique</title>
            <informaltable frame="all">
               <tgroup cols="2">
                  <colspec colname="c1" colnum="1" colwidth="1*"/>
                  <colspec colname="c2" colnum="2" colwidth="7.87*"/>
                  <tbody>
                     <row>
                        <entry>Datatype</entry>
                        <entry role="datatype">xs:boolean</entry>
                     </row>
                     <row>
                        <entry>Cardinality</entry>
                        <entry role="cardinality">1..1</entry>
                     </row>
                     <row>
                        <entry role="description" namest="c1" nameend="c2">
                           Usually the combination of agency and id (ignoring different versions) is unique. If isUniversallyUnique is set to true, it indicates that the id itsef is universally unique (unique across systems and/or agencies) and therefore the agency part is not required to ensure uniqueness. Default value is false.
                        </entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
         </sect3>
         <sect3 xml:id="ddi4-e162060d-a197-456d-9837-d0dad3f78c3d-properties-isPersistent">
            <title>isPersistent</title>
            <informaltable frame="all">
               <tgroup cols="2">
                  <colspec colname="c1" colnum="1" colwidth="1*"/>
                  <colspec colname="c2" colnum="2" colwidth="7.87*"/>
                  <tbody>
                     <row>
                        <entry>Datatype</entry>
                        <entry role="datatype">xs:boolean</entry>
                     </row>
                     <row>
                        <entry>Cardinality</entry>
                        <entry role="cardinality">1..1</entry>
                     </row>
                     <row>
                        <entry role="description" namest="c1" nameend="c2">
                           Usually the content of the current version is allowed to change, for example as the contibutor is working on the object contents. However, when isPersistent is true, it indicates the there will be no more changes to the current version. Default value is false.
                        </entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
         </sect3>
         <sect3 xml:id="ddi4-e162060d-a197-456d-9837-d0dad3f78c3d-properties-localId">
            <title>localId</title>
            <informaltable frame="all">
               <tgroup cols="2">
                  <colspec colname="c1" colnum="1" colwidth="1*"/>
                  <colspec colname="c2" colnum="2" colwidth="7.87*"/>
                  <tbody>
                     <row>
                        <entry>Datatype</entry>
                        <entry role="datatype">LocalId</entry>
                     </row>
                     <row>
                        <entry>Cardinality</entry>
                        <entry role="cardinality">0..n</entry>
                     </row>
                     <row>
                        <entry role="description" namest="c1" nameend="c2">
                           This is an identifier in a given local context that uniquely references an object, as opposed to the full ddi identifier which has an agency plus the id. For example, localId could be a variable name in a dataset.
                        </entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
         </sect3>
         <sect3 xml:id="ddi4-e162060d-a197-456d-9837-d0dad3f78c3d-properties-basedOnObject">
            <title>basedOnObject</title>
            <informaltable frame="all">
               <tgroup cols="2">
                  <colspec colname="c1" colnum="1" colwidth="1*"/>
                  <colspec colname="c2" colnum="2" colwidth="7.87*"/>
                  <tbody>
                     <row>
                        <entry>Datatype</entry>
                        <entry role="datatype">BasedOnObject</entry>
                     </row>
                     <row>
                        <entry>Cardinality</entry>
                        <entry role="cardinality">0..1</entry>
                     </row>
                     <row>
                        <entry role="description" namest="c1" nameend="c2">
                           The object/version that this object version is based on.
                        </entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
         </sect3>
      </sect2>
      <sect2 xml:id="ddi4-e162060d-a197-456d-9837-d0dad3f78c3d-relationships" revision="" role="relationships">
         <title>Relationships</title>
         <sect3 xml:id="ddi4-e162060d-a197-456d-9837-d0dad3f78c3d-relationships-hasAnnotation">
            <title>hasAnnotation</title>
            <informaltable frame="all">
               <tgroup cols="2">
                  <colspec colname="c1" colnum="1" colwidth="1*"/>
                  <colspec colname="c2" colnum="2" colwidth="7.87*"/>
                  <tbody>
                     <row>
                        <entry>Target</entry>
                        <entry>
                           <link linkend="ddi4-81534c85-a7ad-4bc9-a276-9ec62a285aa9">
                           Annotation</link>
                        </entry>
                     </row>
                     <row>
                        <entry>Type</entry>
                        <entry>Aggregation</entry>
                     </row>
                     <row>
                        <entry>Source Cardinality</entry>
                        <entry>0..1</entry>
                     </row>
                     <row>
                        <entry>Target Cardinality</entry>
                        <entry>1..n</entry>
                     </row>
                     <row>
                        <entry namest="c1" nameend="c2">
                           Provides annotation information on the object to support citation and crediting of the creator(s) of the object.
                        </entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
         </sect3>
      </sect2>
   </sect1>
   <sect1 xml:id="ddi4-0411fa15-42da-4060-b78d-558b9086d700">
      <title>Identifiable</title>
      <sect2 revision="" role="is_abstract">
         <title>Abstract</title>
         <para>This class is abstract</para>
      </sect2>
      <sect2 xml:id="ddi4-0411fa15-42da-4060-b78d-558b9086d700-definition" revision="" role="definition">
         <title>Definition</title>
         <para>
            Used to identify objects for purposes of internal and/or external referencing. Elements of this type are versioned. Most objects except for the ComplexDataTypes will inherit from Identifiable or the more specialised AnnotatedIdentfiable.
         </para>
      </sect2>
      <sect2 xml:id="ddi4-0411fa15-42da-4060-b78d-558b9086d700-properties" revision="" role="properties">
         <title>Properties</title>
         <sect3 xml:id="ddi4-0411fa15-42da-4060-b78d-558b9086d700-properties-agency">
            <title>agency</title>
            <informaltable frame="all">
               <tgroup cols="2">
                  <colspec colname="c1" colnum="1" colwidth="1*"/>
                  <colspec colname="c2" colnum="2" colwidth="7.87*"/>
                  <tbody>
                     <row>
                        <entry>Datatype</entry>
                        <entry role="datatype">xs:string</entry>
                     </row>
                     <row>
                        <entry>Cardinality</entry>
                        <entry role="cardinality">1..1</entry>
                     </row>
                     <row>
                        <entry role="description" namest="c1" nameend="c2">
                           This is the registered agency code with optional sub-agencies separated by dots. For example, diw.soep, ucl.qss, abs.essg.
                        </entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
         </sect3>
         <sect3 xml:id="ddi4-0411fa15-42da-4060-b78d-558b9086d700-properties-id">
            <title>id</title>
            <informaltable frame="all">
               <tgroup cols="2">
                  <colspec colname="c1" colnum="1" colwidth="1*"/>
                  <colspec colname="c2" colnum="2" colwidth="7.87*"/>
                  <tbody>
                     <row>
                        <entry>Datatype</entry>
                        <entry role="datatype">xs:string</entry>
                     </row>
                     <row>
                        <entry>Cardinality</entry>
                        <entry role="cardinality">1..1</entry>
                     </row>
                     <row>
                        <entry role="description" namest="c1" nameend="c2">
                           The ID of the object. This must conform to the allowed structure of the DDI Identifier and must be unique within the declared scope of uniqueness (Agency or Maintainable).
                        </entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
         </sect3>
         <sect3 xml:id="ddi4-0411fa15-42da-4060-b78d-558b9086d700-properties-version">
            <title>version</title>
            <informaltable frame="all">
               <tgroup cols="2">
                  <colspec colname="c1" colnum="1" colwidth="1*"/>
                  <colspec colname="c2" colnum="2" colwidth="7.87*"/>
                  <tbody>
                     <row>
                        <entry>Datatype</entry>
                        <entry role="datatype">xs:string</entry>
                     </row>
                     <row>
                        <entry>Cardinality</entry>
                        <entry role="cardinality">1..1</entry>
                     </row>
                     <row>
                        <entry role="description" namest="c1" nameend="c2">
                           The version number of the object. The version number is incremented whenever the non-administrative metadata contained by the object changes.
                        </entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
         </sect3>
      </sect2>
   </sect1>
</chapter>

**Comment by borsna** [comment]
This may be able to be fixed in the rendering by parameters to the xslt:s

**Comment by borsna** [comment]
from Achim:

Here are is the option I set for the XSLT configuration for the PDF.

Change the default 2 to 0
<xsl:param name="toc.section.depth">0</xsl:param>
See: http://www.sagehill.net/docbookxsl/TOCcontrol.html#d0e13284


Custom cell padding should be possible with:
<xsl:attribute-set name="table.cell.padding">
  <xsl:attribute name="padding-start">2pt</xsl:attribute>
  <xsl:attribute name="padding-end">2pt</xsl:attribute>
  <xsl:attribute name="padding-top">2pt</xsl:attribute>
  <xsl:attribute name="padding-bottom">2pt</xsl:attribute>
</xsl:attribute-set>
See: http://www.sagehill.net/docbookxsl/CellSpacing.html


Example of customization XSL:
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
               <xsl:import href="file:///D:/DocBook/XSL/docbook-xsl-1.78.1/fo/docbook.xsl"/>
    <xsl:param name="toc.section.depth">0</xsl:param>
</xsl:stylesheet>
See: http://www.sagehill.net/docbookxsl/CustomMethods.html#CustomizationLayer


Achim

**Comment by spuddybike** [comment]
This can be closed - as we are no longer using docbook
