### ISSUE TITLE
Insert ddi-logo.svg on the docbook frontpage

### ISSUE THREAD

**Issue by borsna** [ddialliance/lion#51]
It is posible to do this as inline svg, works fine in oxygen when editing but not when rendering.
Is there a reference somewhere on how to do this?

**Comment by accc** [comment]
Olof
This is one I parked whilst I got on with other things

Here’s the simple answer
http://www.docbook.org/tdg5/en/html/cover.html
and this is the more complicated actual answer
http://www.dpawson.co.uk/docbook/styling/titlepage.html

though this might be a simpler solution
http://www.oxygenxml.com/forum/topic5845.html#p18225

thanks
Jon

**Comment by borsna** [comment]
Johanna and Achim is working on this

**Comment by spuddybike** [comment]
This can be closed - as we are no longer using docbook

**Comment by spuddybike** [comment]
This can be closed - as we are no longer using docbook
