### ISSUE TITLE
Cardinalities missing in XMI export

### ISSUE THREAD

**Issue by OliverHopt** [ddialliance/lion#61]
There are a few cardinalities in the content, that are not included in the output as XMI. One example is the property target cardinality 2..2 of the propperts maps in AgentSimilarityPair.

**Comment by OliverHopt** [comment]
some more examples on: https://ddi-alliance.atlassian.net/browse/DMT-108

**Comment by borsna** [comment]
as i wrote in [DMT-108](https://ddi-alliance.atlassian.net/browse/DMT-108), is this just a matter of adding ``2..2`` in the list of cardinalities?

**Comment by borsna** [comment]
deployed https://github.com/ddialliance/lion/commit/6b7b1c7e1ec9f5bb2124430b2064edb0d919b6a1 to production. @OliverHopt is this resolved?

**Comment by OliverHopt** [comment]
Solved
